### ISSUE TITLE
1

### ISSUE THREAD

**Issue by Ingvarr71** [StagOS/manifest#2]
Hello! I am collecting 10 android, help solve the error.

[ 38% 48095/123628] build out/target/product/twolip/obj/ETC/sepolicy.recovery_intermediates/sepolicy
FAILED: out/target/product/twolip/obj/ETC/sepolicy.recovery_intermediates/sepolicy
/bin/bash -c "(ASAN_OPTIONS=detect_leaks=0 out/host/linux-x86/bin/checkpolicy -M -c 		30 -o out/target/product/twolip/obj/ETC/sepolicy.recovery_intermediates/sepolicy.tmp out/target/product/twolip/obj/ETC/sepolicy.recovery_intermediates/sepolicy.recovery.conf ) && (out/host/linux-x86/bin/sepolicy-analyze out/target/product/twolip/obj/ETC/sepolicy.recovery_intermediates/sepolicy.tmp permissive > out/target/product/twolip/obj/ETC/sepolicy.recovery_intermediates/sepolicy.permissivedomains ) && (if [ \"userdebug\" = \"user\" -a -s out/target/product/twolip/obj/ETC/sepolicy.recovery_intermediates/sepolicy.permissivedomains ]; then 		echo \"==========\" 1>&2; 		echo \"ERROR: permissive domains not allowed in user builds\" 1>&2; 		echo \"List of invalid domains:\" 1>&2; 		cat out/target/product/twolip/obj/ETC/sepolicy.recovery_intermediates/sepolicy.permissivedomains 1>&2; 		exit 1; 		fi ) && (mv out/target/product/twolip/obj/ETC/sepolicy.recovery_intermediates/sepolicy.tmp out/target/product/twolip/obj/ETC/sepolicy.recovery_intermediates/sepolicy )"
device/xiaomi/sdm660-common/sepolicy/vendor/hal_power_default.te:2:ERROR 'unknown type debugfs_wlan' at token ';' on line 88631:
allow hal_power_default debugfs_wlan:dir { open getattr read search ioctl lock };
#line 2
checkpolicy:  error(s) encountered while parsing configuration
03:44:25 ninja failed with: exit status 1

**Comment by Rpingat** [comment]
Sir you're not supposed to post this here

**Comment by Andrzej6b** [comment]
S

**Comment by Rasenkai** [comment]
> Hello! I am collecting 10 android, help solve the error.
> 
> [ 38% 48095/123628] build out/target/product/twolip/obj/ETC/sepolicy.recovery_intermediates/sepolicy
> FAILED: out/target/product/twolip/obj/ETC/sepolicy.recovery_intermediates/sepolicy
> /bin/bash -c "(ASAN_OPTIONS=detect_leaks=0 out/host/linux-x86/bin/checkpolicy -M -c 30 -o out/target/product/twolip/obj/ETC/sepolicy.recovery_intermediates/sepolicy.tmp out/target/product/twolip/obj/ETC/sepolicy.recovery_intermediates/sepolicy.recovery.conf ) && (out/host/linux-x86/bin/sepolicy-analyze out/target/product/twolip/obj/ETC/sepolicy.recovery_intermediates/sepolicy.tmp permissive > out/target/product/twolip/obj/ETC/sepolicy.recovery_intermediates/sepolicy.permissivedomains ) && (if [ "userdebug" = "user" -a -s out/target/product/twolip/obj/ETC/sepolicy.recovery_intermediates/sepolicy.permissivedomains ]; then echo "==========" 1>&2; echo "ERROR: permissive domains not allowed in user builds" 1>&2; echo "List of invalid domains:" 1>&2; cat out/target/product/twolip/obj/ETC/sepolicy.recovery_intermediates/sepolicy.permissivedomains 1>&2; exit 1; fi ) && (mv out/target/product/twolip/obj/ETC/sepolicy.recovery_intermediates/sepolicy.tmp out/target/product/twolip/obj/ETC/sepolicy.recovery_intermediates/sepolicy )"
> device/xiaomi/sdm660-common/sepolicy/vendor/hal_power_default.te:2:ERROR 'unknown type debugfs_wlan' at token ';' on line 88631:
> allow hal_power_default debugfs_wlan:dir { open getattr read search ioctl lock };
> #line 2
> checkpolicy: error(s) encountered while parsing configuration
> 03:44:25 ninja failed with: exit status 1
> 
> #### failed to build some targets (03:18:47 (hh:mm:ss))

Ask help over at t.me/HornsOfficial
Also I'd suggest using del.dog for your error logs.

**Comment by itsshashanksp** [comment]
@Rasenkai Plox ask in main group not here

**Comment by itsshashanksp** [comment]
@Rasenkai Btw your error is in your log read it again

**Comment by vjspranav** [comment]
Not the place to be discussing build errors.
